In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]
              ])

In [8]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating arrays

In [18]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=((3, 5)))
random_array

array([[5, 4, 1, 7, 6],
       [2, 3, 6, 1, 0],
       [4, 4, 9, 7, 2]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.13071249, 0.14901389, 0.90317843],
       [0.79651609, 0.83688106, 0.54209318],
       [0.30936753, 0.67344967, 0.56904722],
       [0.60905993, 0.00874365, 0.48930464],
       [0.03652505, 0.99332167, 0.50440237]])

In [29]:
random_array_2.shape

(5, 3)

In [30]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.95857618, 0.6230632 , 0.27876016],
       [0.99764675, 0.81569056, 0.4829582 ],
       [0.45198893, 0.27485705, 0.76338036],
       [0.6050916 , 0.39599672, 0.92779615],
       [0.34984387, 0.49098713, 0.43801727]])

In [31]:
random_array_3.shape

(5, 3)

In [38]:
# Pseudo-random numbers
np.random.seed(seed=0) # use to random not change value of random number
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [39]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])